# Generated by Django 5.2.4 on 2026-04-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectiveServiceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateField()),
                ('registration_method', models.CharField(choices=[('AUTO_SYSTEM', 'Automatic — System (Age 18)'), ('MANUAL_STAFF', 'Manual — Staff Entry'), ('SELF_REPORTED', 'Self-Reported'), ('POSTAL', 'Postal Registration')], default='AUTO_SYSTEM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('ACTIVE', 'Active'), ('EXEMPT', 'Exempt'), ('DEREGISTERED', 'Deregistered — Age 26+'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('is_exempt', models.BooleanField(default=False)),
                ('exemption_reason', models.CharField(blank=True, choices=[('ACTIVE_DUTY', 'Active Duty Military'), ('DIPLOMATIC', 'Diplomatic Visa'), ('PRIOR_SERVICE', 'Prior Military Service'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('exemption_notes', models.TextField(blank=True, null=True)),
                ('deregistered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selective_service', to='persons.person')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selective_service_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
