# Generated by Django 5.2.4 on 2026-04-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('REGISTRAR', 'Registrar'), ('DMV', 'DMV'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('AUDITOR', 'Auditor'), ('ELECTIONS', 'Elections'), ('STATE_DEPT', 'State Department'), ('SSA', 'Social Security Administration')], max_length=50, null=True),
        ),
    ]
