# Generated by Django 5.2.4 on 2026-04-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Set by DeathRecord — triggers cascade suspensions', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other / Not Specified')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, help_text='Birth surname before any name change', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='citizenship_status',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident'), ('VISA_HOLDER', 'Visa Holder'), ('UNDOCUMENTED_ALIEN', 'Undocumented Alien'), ('OTHER', 'Other')], default='CITIZEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
