# Generated by Django 5.2.4 on 2026-04-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person_photos/history/')),
                ('is_current', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Initial Registration'), ('UPDATE', 'Routine Update'), ('ID_RENEWAL', 'ID Renewal'), ('PASSPORT', 'Passport Application'), ('COURT_ORDER', 'Court Order'), ('OTHER', 'Other')], default='REGISTRATION', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='persons.person')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
