# Generated by Django 5.2.4 on 2026-04-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('date_of_marriage', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=255)),
                ('officiant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('officiant_title', models.CharField(blank=True, max_length=100, null=True)),
                ('witness_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('witness_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_1_new_last_name', models.CharField(blank=True, help_text='New surname for spouse 1 after marriage (blank = no change)', max_length=100, null=True)),
                ('spouse_2_new_last_name', models.CharField(blank=True, help_text='New surname for spouse 2 after marriage (blank = no change)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Married'), ('DIVORCED', 'Divorced'), ('ANNULLED', 'Annulled'), ('WIDOWED', 'Widowed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriage_certificates_filed', to=settings.AUTH_USER_MODEL)),
                ('spouse_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriages_as_spouse_1', to='persons.person')),
                ('spouse_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriages_as_spouse_2', to='persons.person')),
            ],
        ),
    ]
