# Generated by Django 5.2.4 on 2026-04-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('date_of_death', models.DateField()),
                ('time_of_death', models.TimeField(blank=True, null=True)),
                ('place_of_death', models.CharField(max_length=255)),
                ('cause_of_death', models.TextField()),
                ('cause_category', models.CharField(choices=[('NATURAL', 'Natural Causes'), ('ACCIDENT', 'Accidental'), ('HOMICIDE', 'Homicide'), ('SUICIDE', 'Suicide'), ('UNDETERMINED', 'Undetermined'), ('PENDING', 'Pending Investigation')], default='PENDING', max_length=20)),
                ('manner_of_death', models.TextField(blank=True, null=True)),
                ('attending_physician', models.CharField(blank=True, max_length=255, null=True)),
                ('coroner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_examiner', models.CharField(blank=True, max_length=255, null=True)),
                ('funeral_home', models.CharField(blank=True, max_length=255, null=True)),
                ('burial_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records_filed', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_record', to='persons.person')),
            ],
        ),
    ]
